language: java
jdk:
  - oraclejdk8

sudo: required

services:
  - docker

script:
  - ./mvnw verify -B
  - ./mvnw -Ddocker.username=$DOCKER_USERNAME -Ddocker.password=$DOCKER_PASSWORD docker:push

cache:
  directories:
  - $HOME/.m2