language: java
jdk:
  - oraclejdk8

sudo: required

services:
  - docker

before_script:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

script:
  - ./mvnw package -B
  - ./mvnw -Ddocker.username=$DOCKER_USERNAME -Ddocker.password=$DOCKER_PASSWORD docker:push -B

cache:
  directories:
  - $HOME/.m2
