branch-defaults:
  master:
    environment: prod
global:
  application_name: codegolf
  default_ec2_keyname: dasniko
  default_platform: 64bit Amazon Linux 2016.09 v2.2.2 running Docker 1.11.2
  default_region: eu-west-1
  profile: null
  sc: git
