management:
  context-path: /management

keycloak:
  resource: codegolf
  realm: dukecon-developer
  auth-server-url: https://keycloak.dukecon.org/auth
  realm-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiU9WAAUts6KWKminV7FB3XZV7fDUt++SFc0qV1Fo3Zt1MXNTqPjRNMGUJUdZ7w7z1FX/xQWGa43yYhtC8m5m7COtNyLUVok1nSHZzcN5/2+KE2HyFwfmqRZXM1QwUxLOqL2sJggboRKKw+QHgl2H7ppvMCsNAiCr92Q7lWXub9GYO59DiD7rP3Xq5H5fJBv9IePb3PPOQQ52mhxOrnPvc4IQ53XLNDwqOT1w6s6T1vrDcPP+EoPt7O5dJ3qmSBJXdPgVcYasTQBrUSsJHxxn7VOWWOyn9x5VOvwuRYiMGwBhth+QgNBP4YhyjoBi9MmwRE8Q7P7CmcUimgIonalBAQIDAQAB
  credentials:
    secret: 23fec5c8-b260-4c7c-942c-bbb4d79e606e
  ssl-required: external
  principal-attribute: preferred_username
  disable-trust-manager: true
  securityConstraints:
    - securityCollections:
      - name: protected
        patterns:
          - /play
        authRoles:
          - user
